const SET_MESSAGE = "SET_MESSAGE";
const SET_LOADING = "SET_LOADING";
const ADD_DIAGNOSIS = "ADD_DIAGNOSIS";
const ADD_PRESCRIPTION = "ADD_PRESCRIPTION";
const REMOVE_DIAGNOSIS = "REMOVE_DIAGNOSIS";
const REMOVE_PRESCRIPTION = "REMOVE_PRESCRIPTION";

export {
    SET_LOADING,
    SET_MESSAGE,
    ADD_DIAGNOSIS,
    ADD_PRESCRIPTION,
    REMOVE_DIAGNOSIS,
    REMOVE_PRESCRIPTION
}